#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Note that on the second run, the patch will not apply cleanly
git apply $SCRIPT_DIR/demo-prep.patch

idea $SCRIPT_DIR/..
